### ISSUE TITLE
404 etc should not be turned into exceptions and logged in Elmah

### ISSUE THREAD

**Issue by christensena** [rdingwall/elmah-contrib-webapi#13]
We were perplexed recently after upgrading some Nuget packages to find that we were getting this "HttpException: Found" errors with no stack trace in our Elmah logs.

Turns out that redirects were being treated as errors. Looking the latest code I can immediately see the problem.

I tried adding an elmah filter to my global.asax but this was being ignored (not by elmah but by this attribute).

**Comment by sheam** [comment]
Is there anyway this could be configurable. In the development phase, I find that 400 errors can be valuable to log.
