### ISSUE TITLE
Installing NuGet package breaks build.

### ISSUE THREAD

**Issue by kehollin** [rdingwall/elmah-contrib-webapi#14]
I didn't take the time to determine what all would be required to fix it or what exactly the incompatibilities were, but multiple other packages were updated to incompatible versions. Here's the diffs I found in .csproj of my project:

Deleted:
\<Reference 
    Include="System.Net.Http.Formatting, Version=4.0.0.0, Culture=neutral, 
    PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL"\>

\<Reference 
    Include="System.Web.Http, Version=4.0.0.0, Culture=neutral, 
    PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL"\>

\<Reference 
    Include="System.Web.Http.WebHost, Version=4.0.0.0, Culture=neutral, 
    PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL"\>

\<Reference 
    Include="System.Web.Http.Tracing, Version=4.0.0.0, Culture=neutral, 
    PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL"\>

\<Reference 
    Include="System.Web.Http.OData, Version=4.0.0.0, Culture=neutral, 
    PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL"\>

Added:
\<Reference 
    Include="System.Net.Http.Formatting, Version=5.1.0.0, Culture=neutral, 
    PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL"\>

\<Reference 
    Include="System.Web.Http, Version=5.1.0.0, Culture=neutral, 
    PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL"\>

\<Reference 
    Include="System.Web.Http.OData, Version=4.0.0.0, Culture=neutral, 
    PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL"\>

\<Reference 
    Include="System.Web.Http.Tracing, Version=4.0.0.0, Culture=neutral, 
    PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL"\>

\<Reference 
    Include="System.Web.Http.WebHost, Version=4.0.0.0, Culture=neutral, 
    PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL"\>

**Comment by rdingwall** [comment]
Hi @kehollin, sorry about this - dependencies should be streamlined a bit in the latest version 1.0.10.25.
