### ISSUE TITLE
Could not load file or assembly 'System.Web.Http error

### ISSUE THREAD

**Issue by mattkemp** [rdingwall/elmah-contrib-webapi#23]
After installing the nuget package into my MVC and Web API project I get the following error:

Could not load file or assembly 'System.Web.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

reinstalling WebAPI via the following Nuget console command
Update-Package Microsoft.AspNet.WebApi -reinstall

results in a couple of errors:
1. System.Web.Http.ExceptionHandling isn't recognised any more
2. In global.asax.cs  GlobalConfiguration.Configuration.Filters.Add(new ElmahHandleErrorApiAttribute()); is erroring as ElmahHandleErrorApiAttribute isn't an IFilter.

removing Elmah.Contrib.WebApi and reinstalling Microsoft.AspNet.WebApi puts everything back how it was - but no error logging in the WebApi calls.

**Comment by rdingwall** [comment]
Hi @mattkemp I'm not actively maintaining this project any more. However it's really only 2 files so I recommend simply dropping them into your solution directly, and changing whichever signature you need to support the new framework interface (if it has changed).

https://github.com/rdingwall/elmah-contrib-webapi/blob/master/src/Elmah.Contrib.WebApi/ElmahExceptionLogger.cs

https://github.com/rdingwall/elmah-contrib-webapi/blob/master/src/Elmah.Contrib.WebApi/ElmahHandleErrorApiAttribute.cs

Sorry - hope this helps!

**Comment by mattkemp** [comment]
Thanks Richard!
I had an old version of WebAPI which I uninstalled and put in Web API 2.2, it doesn't seem to have broken anything and now System.Web.Http.ExceptionHandling is available.

**Comment by mattkemp** [comment]
also I removed the global.asax.cs line, and just left the WebApiConfig.cs line in there as it was logging two elmah errors per exception.
